fix: change os.Getenv("VIRTUAL_HOST"), rename Add/Added in controllers and dtos, remove all omitempty and fix swagger
speedianet/os pull request #19
Opened 2024-02-06 22:39 UTC by polillomm

2024-02-26 12:40 UTC, ntorga commented on src/domain/useCase/createAccount.go
> +		trashDirPermissions, _ := valueObject.NewUnixFilePermissions("775")
755

Apesar de que permissões no DTO de CreateFile deveria ser um ponteiro. Se a pessoa não enviar, significa que devemos usar o 644 para arquivos e 755 para diretórios automaticamente lá na infra.

2024-02-26 12:46 UTC, ntorga commented on src/infra/files/filesQueryRepo.go
> +	shouldReturnContent := false
shouldReturnContent não era true caso o filesToFactory fosse igual a 1? Por que ele se repete aqui então?

2024-02-26 12:49 UTC, ntorga commented on src/infra/files/filesQueryRepo.go
> +		unixFile, err := repo.unixFileFactory(fileToFactory, shouldReturnContent)
Dentro do laço, você tem um contexto micro, portanto, não é preciso variáveis verbosas tais como filePathIsDir. Apenas isDirectory é o suficiente para quem está lendo entenda. Até mesmo a variável fileToFactory poderia ser apenas file. Lembre-se, nomes exportados, tais como nome de VO, métodos, etc, precisam ser mais elaborados para designar sua função. Já num ambiente micro, tais como dentro de um método, switch/if/for etc você já tem um contexto mais focado, onde não é preciso ficar se repetindo. Você só precisaria usar fileToFactory aqui se dentro do mesmo loop tivesse outro tipo de file, entende? Equilibrar a verbosidade, nem muito, nem pouco.

2024-02-26 12:51 UTC, ntorga commented on src/presentation/api/controller/filesController.go
> +
Você não possui um helper chamado ParseBool? Acho que aqui é um local para usá-lo.

2024-02-26 12:51 UTC, ntorga commented on src/presentation/api/controller/filesController.go
> +	}
Usar ParseBool helper.

2024-02-26 12:52 UTC, ntorga commented on src/presentation/cli/controller/runtimeController.go
> +	if hostnameStr == "" {
Isso é um else amigo.

2024-02-26 20:55 UTC, ntorga requested changes

2024-02-26 20:55 UTC, ntorga commented on src/infra/vhost/virtualHostQueryRepo.go
> +		isPrimary := serverName == primaryHostname
Você já não tem essa informação na linha 62?

2024-02-26 20:55 UTC, ntorga commented on src/infra/files/filesQueryRepo.go
> +	shouldReturnContent := false
Esse aqui continua sem resposta.

2024-02-26 20:55 UTC, ntorga commented on src/infra/services/addInstallable.go
>  		"/app/conf/php/primary.conf",
Esse diretório /app/conf tá sendo usado bastante nesse arquivo, talvez exportá-lo como constante faça sentido.

2024-02-26 20:55 UTC, ntorga commented on src/infra/database/databaseCmdRepo.go
> +func (repo DatabaseCmdRepo) AddUser(addDatabaseUser dto.CreateDatabaseUser) error {
Hmmm, pq o DTO chama CreateDatabaseUser e a função não chama CreateUser?

2024-02-26 20:55 UTC, ntorga commented on src/domain/useCase/deleteUnixFiles.go
> +		trashDirPermissions, _ := valueObject.NewUnixFilePermissions("775")
755

2024-02-26 20:55 UTC, ntorga commented on src/domain/useCase/createAccount.go
> +	}
Hehehe, eu falei ali em baixo pra mudar pra 755, só que lembrava de já ter pedido isso. Esse código tá se repetindo. Cria um método auxiliar chamado CreateTrash lá no delete e usa ele aqui. Daí você coloca um retorno de error apenas e faz a checagem de a trash existe dentro dele, só tu passar a filesQueryRepo pra ele.

2024-02-27 16:01 UTC, polillomm commented on src/infra/services/addInstallable.go
>  		"/app/conf/php/primary.conf",
Ajustado.

2024-02-27 16:47 UTC, ntorga requested changes

2024-02-27 16:47 UTC, ntorga commented on src/infra/files/filesCmdRepo.go
>  }
Eu falei pra tu fazer na infra, mas relendo aqui, colocar 644 pra arquivo e 755 pra diretório é uma regra nossa, de negócio. Que tal colocar um check pra ver se o Permissions == nil lá no New do dto.CreateUnixFile e criar por lá essa ideia de 755 pra dir e 644 pra arquivo? Assim ele vai ser ponteiro no New, mas não na struct, portanto, você vai conseguir consumir diretamente quando a struct tiver construída. (:

2024-02-27 16:47 UTC, ntorga commented on src/infra/services/addCustom.go
>  func AddCustom(
Tem bastante "Add" e "add" pelo código, dá uma geral por favor.

2024-02-27 17:41 UTC, polillomm commented on src/infra/services/addCustom.go
>  func AddCustom(
Ajustei em todo o PR!

2024-02-27 18:31 UTC, polillomm commented on src/infra/files/filesCmdRepo.go
>  }
Show de bola, fica muito melhor desse jeito!
Detalhe que com o construtor sendo um ponteiro e o DTO não fica claro que o arquivo ou diretório SEMPRE terá permissão, mas que a atribuição dela não precisa ser feita obrigatoriamente. Sensacional!

2024-02-27 19:50 UTC, ntorga approved these changes

2024-02-27 19:50 UTC, merged