feat: implements postgres
speedianet/os pull request #20
Opened 2024-02-26 07:47 UTC by polillomm

2024-02-26 07:48 UTC, polillomm commented
@ntorga

2024-02-28 12:16 UTC, ntorga commented on src/infra/database/postgresDatabaseCmdRepo.go
> +func (repo PostgresDatabaseCmdRepo) addPermissionsToUser(
Você está acessando o dbUser.String() 3x. Nessas situações devemos fazer o que mesmo?

2024-02-28 12:16 UTC, ntorga commented on src/infra/database/postgresDatabaseCmdRepo.go
> +	dbNameStr := dbName.String()
Aqui você fez o certo para o dbName, mas esqueceu o dbUser.

2024-02-28 12:17 UTC, ntorga commented on src/infra/database/postgresDatabaseCmdRepo.go
> +	return err
Qual a necessidade da separação dessas operações em dois métodos? Se a responsabilidade é permitir o usuário de ter acesso à um base/schema/sequence, portanto, é uma responsabilidade única.

2024-02-28 12:19 UTC, ntorga commented on src/infra/database/postgresDatabaseCmdRepo.go
> +func (repo PostgresDatabaseCmdRepo) revokeUserDefaultPermissions(
Você não está removendo os privs das schemas e sequences antes de revogar os privs da base.

2024-02-28 12:20 UTC, ntorga commented on src/infra/database/postgresDatabaseQueryRepo.go
> +	return infraHelper.RunCmd("psql", psqlArgs...)
Que malabarismo é esse aqui jovem?

2024-02-28 12:21 UTC, ntorga commented on src/infra/database/postgresDatabaseQueryRepo.go
> +		if regexp.MustCompile(dbExcludeRegex).MatchString(dbName) {
Por que o MustCompile dentro do loop e não fora? Não tem sentido algum fazer isso.

2024-02-28 12:22 UTC, ntorga commented on src/infra/database/postgresDatabaseQueryRepo.go
> +		}
Sem log? Por que? É um factory jovem, sem log aqui nunca vamos saber por que uma dbName não tá sendo exibida.

2024-02-28 12:24 UTC, ntorga commented on src/infra/database/postgresDatabaseQueryRepo.go
> +	dbDataclStr, err := PostgresqlCmd(
O que é Datacl? O que essa variável armazena?

2024-02-28 12:25 UTC, ntorga commented on src/infra/database/postgresDatabaseQueryRepo.go
> +
Você não vai checar se tá vazia antes do loop?

2024-02-28 12:28 UTC, ntorga commented on src/infra/database/postgresDatabaseQueryRepo.go
> +		dbUserStr := dbUserMatch[1]
Eu posso estar errado, mas se você só precisa da [1], por que usou All no StringSubmatch?

2024-02-28 12:28 UTC, ntorga commented on src/infra/database/postgresDatabaseQueryRepo.go
> +		return databases, errors.New("GetDatabaseNamesError")
Não fazemos assim cara, retornamos o erro pro UC fazer o log, como você fez no código o tempo todo.

2024-02-28 12:29 UTC, ntorga commented on src/infra/database/postgresDatabaseQueryRepo.go
> +			log.Printf("FailedToGetDatabaseSize (%s): %s", dbName.String(), err.Error())
Não há necessidade de logar isso. Setar pra zero é o suficiente em caso de falha aqui.

2024-02-28 12:30 UTC, ntorga commented on src/infra/database/postgresDatabaseQueryRepo.go
> +		dbUsernames, err := repo.getDatabaseUsernames(dbName)
dbUsernames já será uma []valueObject.DatabaseUsername{} mesmo em caso de erro por conta de como você construiu a getDatabaseUsernames().

2024-02-28 12:45 UTC, ntorga commented on src/presentation/api/router.go
> +	databaseGroup := baseRoute.Group("/database", apiMiddleware.ServiceStatusValidator(dbServices))
Sua lógica está fundamentalmente incorreta aqui.

Se você testar sua API com um cliente HTTP, vai ver que consegue operar o MySQL se o PostgreSQL estiver instalado e vice-versa, pois a sua CheckServices verifica se UM dos itens está instalado e não O ITEM necessário.

A lógica correta aqui é descobrir qual é o dbType ANTES e continuar passando para o ServiceStatusValidator apenas uma string e não um slice.

A propósito, acredito que o mesmo se aplica no runtime/php, que aparentemente não consome o ServiceStatusValidator.

2024-02-28 15:34 UTC, polillomm commented on src/infra/database/postgresDatabaseCmdRepo.go
> +func (repo PostgresDatabaseCmdRepo) addPermissionsToUser(
Ajustado.

2024-02-28 15:35 UTC, polillomm commented on src/infra/database/postgresDatabaseCmdRepo.go
> +	dbNameStr := dbName.String()
Ajustado.

2024-02-28 16:05 UTC, polillomm commented on src/infra/database/postgresDatabaseQueryRepo.go
> +	return infraHelper.RunCmd("psql", psqlArgs...)
Ficou super confuso mesmo, mas o problema foi o fato de eu não ter ido atrás sobre a flag "-d". Essa mudança no comando "psql" foi necessária, pois diferentemente do MySQL, o Postgres precisa que você esteja conectado no respectivo database pra fazer certas modificações.

Uma pesquisa rapidinha me mostrou que a flag "-d" pode ser adicionada no final do código, portanto deu pra tirar todo esse carnaval daí e deixar só o que importa mesmo.

2024-02-28 16:07 UTC, polillomm commented on src/infra/database/postgresDatabaseQueryRepo.go
> +		if regexp.MustCompile(dbExcludeRegex).MatchString(dbName) {
Ajustado.
Eu mesmo consegui enxergar esse problema. Falta de atenção.

2024-02-28 16:09 UTC, polillomm commented on src/infra/database/postgresDatabaseQueryRepo.go
> +		}
Ajustado.
Falta de atenção novamente, deveria ter um log com o erro do VO e o valor que foi enviado pra lá.

2024-02-28 16:29 UTC, polillomm commented on src/infra/database/postgresDatabaseQueryRepo.go
> +		dbUserStr := dbUserMatch[1]
Porque a coluna datacl me retorna os usuários e suas permissões encodados.

O formato é esse, por exemplo: `{=Tc/postgres,postgres=CTc/postgres,mmp=CTc/postgres}`.
Se eu utilizar o StringSubmatch apenas ao invés do AllStringSubmatch, eu só terei acesso a primeira ocorrênica, que seria o "postgres". Mas, como eu gostaria de coletar todos os usuários com permissões, eu uso o AllStringSubmatch para que eu seja capaz de coletar todas as ocorrências, ou seja, no meu exemplo anterior eu conseguiria trazer não apenas o "postgres", mas o "mmp" também.

Tem um exemplo da utilização desses dois métodos para o mesmo fim: https://goplay.tools/snippet/SUL8FMIndOk

2024-02-28 16:30 UTC, polillomm commented on src/infra/database/postgresDatabaseQueryRepo.go
> +
O loop só vai ser executado caso realmente tenha alguém dentro do meu slice. Se ele estiver vazio, ele só vai cair no return e voltar vazio.

2024-02-28 16:36 UTC, polillomm commented on src/infra/database/postgresDatabaseQueryRepo.go
> +		return databases, errors.New("GetDatabaseNamesError")
Falta de atenção, isso foi um log de debug que deveria ter sido removido.

2024-02-28 17:33 UTC, polillomm commented on src/infra/database/postgresDatabaseCmdRepo.go
> +	return err
Ajustado.

2024-02-28 17:34 UTC, polillomm commented on src/infra/database/postgresDatabaseCmdRepo.go
> +func (repo PostgresDatabaseCmdRepo) revokeUserDefaultPermissions(
Explicado em outra conversa sobre o motivo disso.

Resumidamente revogar as permissões a nível database já revoga as permissões dos níveis abaixo.

2024-02-28 17:37 UTC, polillomm commented on src/infra/database/postgresDatabaseQueryRepo.go
> +		dbUsernames, err := repo.getDatabaseUsernames(dbName)
Ajustado. Retirei, mas mantive o log.

2024-02-28 22:26 UTC, polillomm commented on src/presentation/api/router.go
> +	databaseGroup := baseRoute.Group("/database", apiMiddleware.ServiceStatusValidator(dbServices))
Ajustado.

2024-02-29 13:02 UTC, ntorga requested changes

2024-02-29 13:02 UTC, ntorga commented on src/presentation/api/controller/databaseController.go
> +var availableServices = []string{"mysql", "postgresql"}
Você quase acertou, mas sua lógica ainda tá desnecessariamente complexa.

O seu CheckServiceAvailability tem o poder de parar a execução, no entanto, Check nos dá a entender que é um retorno boleano.

Vamos voltar pra lógica. Qual é a missão?
Impedir que sejam usados endpoints cujos serviços não estão operacionais

Como deveria chamar o método então? PreventExecutionIfServiceUnavailable(serviceName string).
OU
StopIfServiceUnavailable(serviceName string)

Não é preciso passar para esse helper uma slice de serviços não, você só precisa passar pra ele qual é o serviço que você deseja checar, se é MySQL, se é PostgreSQL ou se é PHP.

Principalmente por que nessa etapa aqui (controller), você agora sabe qual é o dbType, sem precisar parsear a rota (se você quisesse usar ele na rota ao invés do controller, precisaria usar um strings.Contains).

A propósito, eu sugeri serviceName string, mas aparentemente você tá criando um VO do tipo ServiceName sempre que chama ele e depois fazendo .String() o que me parece totalmente desnecessário. Se você já criou o VO, passe o VO jovem, zero necessidade de ser string no param.

Portanto, seu código ainda está bastante longe da solução mais simples e óbvia. É preciso refazer. Te dei a solução, basta implementar.

2024-02-29 14:18 UTC, polillomm commented on src/infra/database/postgresDatabaseQueryRepo.go
> +
Não conheço todas as linguagens, mas em sua grande maioria o bloco de laço só é executado quando tem elementos dentro de um slice/array/list. Fazer uma checagem anterior para evitar que esse bloco seja executado é redundante, justamente porque eu estou tentando reiventar a roda: se o loop não é executado, porque eu verificaria?

Já foge um pouco de programação implícita, vira coisa pra inglês ver.

2024-02-29 14:18 UTC, polillomm commented on src/infra/database/postgresDatabaseQueryRepo.go
> +		dbUserStr := dbUserMatch[1]
Yep, com toda certeza!

2024-02-29 14:22 UTC, polillomm commented on src/infra/database/postgresDatabaseQueryRepo.go
> +
De qualquer forma, adicionei a verificação para fazer o early return e deixar mais fácil a leitura. Mas o motivo da implementação é um improve pro código, porque não vejo alguém não entendendo o método pela falta de checagem pré laço.

2024-02-29 14:42 UTC, polillomm commented on src/infra/database/postgresDatabaseQueryRepo.go
> +	dbType, _ := valueObject.NewDatabaseType("postgres")
Ajustei para o nome principal, agora é "postgresql".

2024-02-29 14:52 UTC, polillomm commented on src/presentation/api/controller/databaseController.go
> +var availableServices = []string{"mysql", "postgresql"}
Ajustado.
Coloquei o nome de StopIfServiceUnavailable para ficar menor, o primeiro nome ficou muito grande.

2024-02-29 16:18 UTC, ntorga requested changes

2024-02-29 16:18 UTC, ntorga commented on src/presentation/shared/helper/stopIfServiceUnavailable.go
> +}
```
for _, availableSvc := range availableSvcs {
	availableSvcName := availableSvc.Name.String()
	if availableSvcName != svcName {
		continue
	}

	if availableSvc.Status.String() != "running" {
		panic("ServiceUnavailable: " + svcName)
	}
}
```

2024-02-29 17:07 UTC, polillomm commented on src/presentation/api/controller/databaseController.go
> +	//sharedHelper.StopIfServiceUnavailable(dbType.String())
//ajustado

2024-02-29 17:10 UTC, polillomm commented on src/presentation/shared/helper/stopIfServiceUnavailable.go
> +}
Ajustado

2024-02-29 18:52 UTC, merged