feat: cache public ip on db
speedianet/os pull request #21
Opened 2024-03-01 15:58 UTC by polillomm

2024-03-01 21:03 UTC, ntorga requested changes

2024-03-01 21:03 UTC, ntorga commented on src/presentation/api/router.go
> +func (router Router) registerApiRoutes(baseRoute *echo.Group) {
Se esse método agora pertence à uma struct, exporte ele. Lá no Control eu costumo chamá-lo de "func (router Router) RegisterRoutes() {".

2024-03-01 21:03 UTC, ntorga commented on src/presentation/cli/router.go
> +func (router Router) registerCliRoutes() {
O que eu falei ali em cima também se aplica aqui.

2024-03-01 21:03 UTC, ntorga commented on src/presentation/cli/cli.go
>  	if err := rootCmd.Execute(); err != nil {
Aproveita que tu tá ajustando aqui e copia o RunRootCmd que uso lá no cli do control:
https://github.com/speedianet/control/blob/main/src/presentation/cli/cli.go#L66

2024-03-04 02:40 UTC, polillomm commented on src/infra/database/internalDatabaseService.go
> +	}
Ajustado.

2024-03-04 02:42 UTC, polillomm commented on src/infra/o11y/o11yQueryRepo.go
> +	}
Ajustado.

2024-03-04 02:43 UTC, polillomm commented on src/infra/o11y/o11yQueryRepo.go
> +	ipStr, err := repo.transientDbSvc.Get("PublicIp")
Ajustado.

2024-03-04 02:45 UTC, polillomm commented on src/infra/o11y/o11yQueryRepo.go
> +	err = repo.transientDbSvc.Set("PublicIp", ipAddress.String())
Ajustado.

2024-03-04 02:55 UTC, polillomm commented on src/infra/o11y/o11yQueryRepo.go
> +		log.Printf("FailedToPersistPublicIp: %s", err.Error())
Aqui eu buguei, foi mal. A ideia é voltar esse erro como todos os outros e logar ele lá no GetOverview do próprio repo?

Algo como, no lugar desse log, fazer um
```
if err != nil {
    return ipAddress, errors.New("FailedToPersistPublicIp :" + err.Error())
}
```

E lá no GetOverview fazer um:
```
publicIpAddress, err := repo.getPublicIpAddress()
if err != nil {
	if !strings.Contains(err.Error(), "FailedToPersistPublicIp") {
		publicIpAddress, _ = valueObject.NewIpAddress("0.0.0.0")
	}

	log.Printf("GetPublicIpAddressError: %s", err.Error())
}
```

É isso? 😅

2024-03-04 02:59 UTC, polillomm commented on src/infra/o11y/o11yQueryRepo.go
> +		return entity.O11yOverview{}, errors.New("GetHardwareSpecsFailed")
Ajustado.
Aproveitei e fiz pro erro de baixo, além de ter declarado uma variável do tipo `entity.O11yOverview` no início do método e retornado ela em todos os casos de construção de entidade pra evitar repetições de `entity.O11yOverview{}` em todo retorno de erro.

2024-03-04 03:05 UTC, polillomm commented on src/infra/database/internalDatabaseService.go
> +package databaseInfra
Ajustado.
Também movi o TransientDatabaseService pra dentro de um dir junto do Internal e chamei o package dos dois de internalDatabaseInfra. Pra não ter confusão, decidi voltar o nome do InternalDatabaseService para o mesmo do Control, então agora eu to chamando ele de PersistentDatabaseService, dessa forma o Transient também conta como um banco interno, só que de cache, assim como o Persistent é interno, mas relacional.

Tudo xeroso.

2024-03-04 03:07 UTC, polillomm commented on src/presentation/api/controller/o11yController.go
> +func (controller O11yController) O11yOverviewController(c echo.Context) error {
Ajustado. Deixei como GetO11yOverview pra ficar parecido com o UC.

2024-03-04 03:07 UTC, polillomm commented on src/presentation/api/router.go
> +func (router Router) registerApiRoutes(baseRoute *echo.Group) {
Esse erro meu foi muito de amador. Eu deveria ter ajustado isso aqui antes de ter pedido review.

Ajustado.

2024-03-04 03:09 UTC, polillomm commented on src/presentation/cli/router.go
> +func (router Router) registerCliRoutes() {
Ajustado.

2024-03-04 03:11 UTC, polillomm commented on src/presentation/cli/cli.go
>  	if err := rootCmd.Execute(); err != nil {
Ajustado.

2024-03-05 13:33 UTC, ntorga requested changes

2024-03-05 13:33 UTC, ntorga commented on src/infra/o11y/o11yQueryRepo.go
> +		log.Printf("FailedToPersistPublicIp: %s", err.Error())
Não.

Nessa função você sempre retorna error, como numa factory, nunca log.

Lá no método principal que chama sua função, você registra o erro via log.Printf e decide se deve ou não parar a execução. No caso da PublicIp, veja que originalmente se o método falhasse, o código defina o publicIp para 0.0.0.0 pois ele não queria parar o fluxo se o IP fosse possível ou não de conseguir. Logo:

```
publicIpAddress, err := repo.getPublicIpAddress()
if err != nil {
	log.Printf("GetPublicIpAddressError: %s", err.Error())
	publicIpAddress, _ = valueObject.NewIpAddress("0.0.0.0")
}
```

Dessa forma, se o usuário pensar "ué, pq o ip público está vindo como 0.0.0.0?", ele vai imediatamente olhar os logs e ver o motivo. No entanto, a request vai retornar 200 OK como deve, pois o ip público é mera informação pra auxiliar o usuário, não algo crucial para nada no OS.

2024-03-05 13:33 UTC, ntorga commented on src/presentation/api/router.go
>  	)
:sob:

2024-03-05 13:33 UTC, ntorga commented on src/presentation/cli/router.go
>  }
:sob:

2024-03-06 18:36 UTC, polillomm commented on src/presentation/api/router.go
>  	)
:point_right: :point_left:

2024-03-06 18:36 UTC, polillomm commented on src/presentation/cli/router.go
>  }
👉 👈

2024-03-06 20:23 UTC, merged