fix: file manager, database and services
speedianet/os pull request #22
Opened 2024-03-08 04:39 UTC by polillomm

2024-03-08 21:38 UTC, ntorga requested changes

2024-03-08 21:38 UTC, ntorga commented on src/presentation/shared/helper/stopIfServiceUnavailable.go
> +		panic("ServiceUnavailable: " + svcName)
Acho que isso está errado.

2024-03-08 21:52 UTC, polillomm commented on src/domain/useCase/deleteUnixFiles.go
> +		isToCleanTrash := fileToDelete.String() == trashDirPath
Ajustado.

2024-03-08 21:54 UTC, polillomm commented on src/infra/files/filesCmdRepo.go
> +		}
Esqueci de remover, era um debug. Ajustado.

2024-03-11 16:04 UTC, polillomm commented on src/infra/files/filesCmdRepo.go
> +			uploadFailure, err := repo.getUploadFailure(err.Error(), fileToUpload)
Troquei pra uploadFailureFactory.

2024-03-11 20:00 UTC, polillomm commented on src/presentation/shared/helper/stopIfServiceUnavailable.go
> +		panic("ServiceUnavailable: " + svcName)
Ajustado.

2024-03-11 20:12 UTC, ntorga approved these changes

2024-03-11 20:12 UTC, merged