fix: file manager (part 2)
speedianet/os pull request #25
Opened 2024-03-15 17:39 UTC by polillomm

2024-03-15 20:48 UTC, ntorga requested changes

2024-03-15 20:48 UTC, ntorga commented on src/domain/valueObject/updateProcessFailure.go
> +	reason string,
String sem validação nem de length não rola em VO cara.

2024-03-15 20:48 UTC, ntorga commented on src/domain/useCase/updateUnixFiles.go
> +func (uc UpdateUnixFiles) updateUnixFilePath(
Renomear para move. Você não precisa ficar repetindo a terminologia Unix em todo método privado. Já sabemos que é UnixFile dentro do método. O termo Unix é importante quando exportado ou transitado entre structs ou camadas. Deixaria um pouco menos verbose se chamasse "moveFile" do que "updateUnixFilePath".

2024-03-15 20:48 UTC, ntorga commented on src/presentation/api/controller/filesController.go
> +// @Param        updateUnixFilesDto 	  body dto.UpdateUnixFiles  true  "UpdateFile"
Melhorar a descrição aqui, informando que apenas X é requerido.

2024-03-15 20:48 UTC, ntorga commented on src/presentation/api/controller/filesController.go
> +	hasFailedPathsWithReason := len(updateProcessInfo.FailedPathsWithReason) > 0
hasSuccess
hasFailures
wasPartiallySuccessful :=  hasSuccess && hasFailures
if wasPartiallySuccessful {

2024-03-18 02:43 UTC, polillomm commented on src/domain/valueObject/updateProcessFailure.go
> +	reason string,
Ajustado.

2024-03-18 02:46 UTC, polillomm commented on src/domain/useCase/updateUnixFiles.go
> +func (uc UpdateUnixFiles) updateUnixFilePath(
Ajustado.

2024-03-18 02:50 UTC, polillomm commented on src/presentation/api/controller/filesController.go
> +// @Param        updateUnixFilesDto 	  body dto.UpdateUnixFiles  true  "UpdateFile"
Ajustado.

2024-03-18 02:52 UTC, polillomm commented on src/presentation/api/controller/filesController.go
> +	hasFailedPathsWithReason := len(updateProcessInfo.FailedPathsWithReason) > 0
Ajustado.

2024-03-18 15:36 UTC, ntorga approved these changes

2024-03-18 15:36 UTC, merged