feat: delete marketplace installed item
speedianet/os pull request #31
Opened 2024-04-17 16:19 UTC by polillomm

2024-04-18 13:19 UTC, ntorga requested changes

2024-04-18 13:19 UTC, ntorga commented on src/infra/marketplace/marketplaceCmdRepo.go
> +	serviceNames []valueObject.ServiceName,
Mais um problema que daria pra ser detectado lendo o código em voz alta e explicando para um leigo. O seu código não é o que você explica. Veja só.

Sua função chama-se "uninstallUnusedServices" e pede um parâmetro chamado "serviceNames []valueObject.ServiceName", logo, assumo que esse serviceNames são os serviços a serem desinstalados.

Daí na linha seguinte, você tem uma variável chamada unusedServiceNames. What? O parâmetro da função já não era os unuseds? Qual a diferença aqui?

Dentro da getInstalledItemUnusedServices() o seu parâmetro "serviceNames" agora se chama "installedItemServices". Wait, what? Não era os serviços a serem desinstalados? Por que está sendo passado para uma função que pega os serviços que não estão em uso pelos serviços a lista de serviços que estão em uso e que em teoria era na vdd a lista de serviços não usados? Caos total no raciocínio, código pra dentro.

Beleza, seguimos na linha 315 e pegamos os itens instalados. Ué, se pegamos os itens instalados, já não vamos pegar os serviços usado inclusive pelo item sendo desinstalado? Por que passaríamos algo pra essa função então se ela não precisa de nada?

Ok, linha 320 se não tiver item instalado, o retorno é a lista de serviços instalados que passamos pra ele. Wait, what? Como não haveria nada instalado se a gente tá removendo um item? O item não existe mais?

Volto a ler o método principal, a sua "uninstallUnusedServices" vem depois do Delete ao banco, ou seja, você não está contando com o item sendo desinstalado no seu for. Beleza, então temos um mau uso de estado aqui. Por isso você sai passando essa lista de serviceNames que eu achei que era serviços não usados e na verdade são serviços usados pelo item a ser desinstalado que não está mais no banco de dados. Tá vendo o nó no raciocínio? Com toda certeza do mundo esse código não é nem de perto o seu pseudo OU o seu pseudo tá todo desorganizado. Imagino que você tenha certeza de que o código funciona, mas funcionar é o mínimo. Explicar pro próximo dev via código como funciona é o objetivo. Não está acontecendo isso, olha a dificuldade da legibilidade que seu código me causa.

Voltamos à linha 325, beleza, tu pegou os serviços em uso e em seguida:
```
if slices.Contains(servicesInUse, serviceName) {
```
		
Que serviceName é esse? Ah tá, serviceName é o iteration do installedServiceNames que eu havia me confundido. Se estamos trabalhando com DOIS tipos de service, os em uso e os installed pq raios não tem um prefixo ali? serviceName é um péssimo nome pra iteration, há DOIS tipos poxa, cadê o prefixo dele? É isso que eu falo, tá vendo como vocês tem mania de abusar da verbosidade onde não deve e esquecer totalmente dela quando deve? Na PR anterior eu falei: "se tem dois do mesmo item num contexto local (for, if, func etc) então você precisa adicionar prefixo. Falamos isso em calls várias vezes e eu já corrigi isso várias vezes. Ainda sim, EXATAMENTE o mesmo erro pois você não tá lendo o código, não tá buscando explicar sua intenção em voz alta.

Ok, voltamos ao método auxiliar, linha 354. Beleza, você tem um for pra desinstalar os serviços que não estão em uso. A mensagem de erro vai passar pra frente qual é o erro no processo de desinstalação, mas ela hora nenhuma menciona qual é o serviço sendo desinstalado. Como eu vou saber que o erro veio da desinstalação do MySQL e não do PHP por exemplo?

Outro ponto que me ocorreu. E se o usuário não quiser remover o MySQL quando ele remove o WordPress? Não damos opção pra ele pra não remover os serviços, o que é uma flag boleana que podemos add no processo de delete pra evitar todo o processo de desinstalação de serviços. Vamos adicionar?

Pronto. Isso é uma leitura em voz alta buscando entender a intenção do seu código. Tá vendo como ela detecta um monte de falha no raciocínio? Novamente, o foco tá em fazer funcionar, não está em fazer funcionar explicando a intenção e não deixando dúvida. Métodos simples, eu não deveria ter tido 1/10 das dúvidas que tive aqui.

2024-04-18 13:19 UTC, ntorga commented on src/infra/marketplace/marketplaceQueryRepo.go
>  	catalogEstimatedSizeBytes := valueObject.Byte(rawCatalogEstimatedSizeBytes)
Byte não aceita interface e usa o helper pra converter interface{} no uint que ele usa? Se não usa, deveria. Daí sua factory aqui seria passar o raw direto pro Byte pois ele já sabe fazer o assert.

2024-04-18 13:19 UTC, ntorga commented on src/presentation/api/controller/marketplaceController.go
> +	)
id é o suficiente. Verbosidade excessiva. A verbosidade deve servir para explicar sua intenção e separar itens parecidos dentro de um mesmo contexto.

2024-04-18 13:19 UTC, ntorga commented on src/domain/repository/marketplaceCmdRepo.go
> +	UninstallItem(installedId valueObject.MarketplaceInstalledItemId) error
No biggie, mas você chamou de installedId aqui e apenas de id na linha 15 do queryRepo. Acho eu que apenas id já dá pra entender sua intenção.

2024-04-18 13:19 UTC, ntorga commented on src/presentation/api/controller/marketplaceController.go
> +// DeleteMarketplaceInstalledItem godoc
Cadê o Delete no CLI querido? Sua PR só veio com o controller na API.

2024-04-18 17:36 UTC, polillomm commented on src/infra/marketplace/marketplaceQueryRepo.go
>  	catalogEstimatedSizeBytes := valueObject.Byte(rawCatalogEstimatedSizeBytes)
Ajustado.
Aproveite e mudei em todos os lugares que usam o próprio struct, agora todos usam o construtor.

2024-04-18 17:53 UTC, polillomm commented on src/presentation/api/controller/marketplaceController.go
> +// DeleteMarketplaceInstalledItem godoc
O marketplace como um todo não tem CLI.
Sabendo disso, foi implementado nessa PR tanto o DELETE, quanto os outros controllers.

2024-04-22 21:09 UTC, ntorga requested changes

2024-04-22 21:09 UTC, ntorga commented on src/presentation/api/controller/marketplaceController.go
> +// @Router       /marketplace/installed/{installedId} [delete]
Faltando um / no final aqui.

2024-04-22 21:09 UTC, ntorga commented on src/presentation/cli/controller/marketplaceController.go
> +			// Format: key:value,key:value
Esse comentário deveria estar no topo do parseDataFields não?

2024-04-22 22:35 UTC, polillomm commented on src/infra/marketplace/marketplaceCmdRepo.go
> +	installedServices []valueObject.ServiceName,
Ajustado.

2024-04-22 22:36 UTC, polillomm commented on src/infra/marketplace/marketplaceCmdRepo.go
> +	servicesInUse, err := repo.getServicesInUse()
Ajustado. Mudei o nome da var também.

2024-04-22 22:37 UTC, polillomm commented on src/infra/marketplace/marketplaceCmdRepo.go
> +	unusedServices := []valueObject.ServiceName{}
Ajustado.

2024-04-22 22:38 UTC, polillomm commented on src/infra/marketplace/marketplaceCmdRepo.go
> +	infraHelper.MakeDir(installDirStr)
Ajustado.
Dá uma olhada pra ver se a mensagem de erro está ok, por gentileza.

2024-04-22 22:43 UTC, polillomm commented on src/presentation/api/controller/marketplaceController.go
> +// @Router       /marketplace/installed/{installedId} [delete]
Real, não tinha notado.
Ajustado, valeu pelo toque!

2024-04-22 22:46 UTC, polillomm commented on src/presentation/cli/controller/marketplaceController.go
> +			// Format: key:value,key:value
Como esse é o único lugar onde será utilizado o DataFields, achei melhor deixar aqui especialmente porque o dev vai visitar essa linha antes da função. Isso evita dele precisar visitar o parse só pra poder descobrir o formato, por exemplo.

Vou deixar esse comentário aqui porque eu acho que ficaria melhor ali mesmo. Se achar que precisa mudar, me avisa por mensagem que eu já troco e subo pro merge!

2024-04-23 12:50 UTC, merged