fix: stop nginx when test failed
speedianet/os pull request #33
Opened 2024-04-26 15:13 UTC by polillomm

2024-04-29 20:48 UTC, ntorga requested changes

2024-04-29 20:48 UTC, ntorga commented on src/infra/services/assets/php/httpd_config.conf
> +  map                     speedia.net *
Dúvida: Sei que o startup vai substituir as menções à speedia.net para o vhost usado, mas e quanto a subdomínio? Será que aqui não deveria ser apenas *?

Um novo vhost no OLS vai criar um novo .conf mas esse aqui é o principal. Será que * funcionaria para incluir qualquer vhost ou teríamos que ficar editando essa linha toda vez que um novo vhost é add no OLS?

2024-04-29 20:48 UTC, ntorga commented on src/infra/services/supervisordFacade.go
>  	case "mariadb":
Acho que dá pra usar case "mariadb", "mysql" por enquanto.

2024-04-30 16:05 UTC, polillomm commented on src/infra/services/assets/php/httpd_config.conf
> +  map                     speedia.net *
Testado exaustivamente. Só o "*" se torna uma configuração inválida, tanto que os listeners ficam vazinhos. É necessário passar o vhost aí.

2024-05-01 22:06 UTC, merged