feat: add swagger missing instructions
speedianet/os pull request #41
Opened 2024-05-20 15:55 UTC by polillomm

2024-06-05 21:01 UTC, ntorga requested changes

2024-06-06 19:27 UTC, polillomm commented on src/presentation/api/controller/marketplaceController.go
> +// @Param        InstallMarketplaceCatalogItem 	  body    dto.InstallMarketplaceCatalogItem  true  "directory is optional. When not provided, directory will be hostname root directory."
Ajustado.

2024-06-06 19:27 UTC, polillomm commented on src/presentation/api/controller/filesController.go
> +// @Param        sourcePaths	body	[]string	true	"File paths that will be deleted"
Ajustado.

2024-06-06 19:29 UTC, polillomm commented on src/presentation/api/controller/databaseController.go
> +// @Param        dbUser path string true "Database username that will be deleted."
Ajustado.

2024-06-06 19:30 UTC, polillomm commented on src/presentation/api/controller/cronController.go
> +// @Param        cronId 	  path   string  true  "Cron ID that will be deleted."
Ajustado.

2024-06-06 19:36 UTC, polillomm commented on src/presentation/api/controller/sslController.go
> +// @Param        createSslPairDto 	  body    dto.CreateSslPair  true  "All props are required.<br />virtualHosts may be string or []string. Alias is not allowed.<br />certificate is a string field, i
Ajustado.

2024-06-06 19:48 UTC, polillomm commented on src/presentation/api/controller/sslController.go
> +// @Param        sslPairId 	  path   string  true  "SSL Pair ID that will be deleted."
Ajustado.

2024-06-07 21:23 UTC, ntorga approved these changes

2024-06-07 21:23 UTC, merged