Feat/add postgresql
speedianet/os pull request #6
Opened 2024-01-07 23:35 UTC by polillomm

2024-01-11 20:22 UTC, ntorga requested changes

2024-01-11 20:22 UTC, ntorga commented on src/infra/services/addInstallable.go
> +		"echo | /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh",
O "bash", "/usr/share[...]" mais normalzinho não funcionou?

2024-01-11 20:28 UTC, polillomm commented on src/infra/services/addInstallable.go
> +		"echo | /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh",
Nope, essa foi a única forma que deu certo pra ignorar o prompt que pede o "ENTER" na instalação. Especificamente usando o echo e o /usr/share[...] na mesma linha :/

2024-01-11 20:28 UTC, polillomm commented on src/infra/database/postgresDatabaseCmdRepo.go
> +	_, err := MysqlCmd(
Resolvido.

2024-01-12 13:46 UTC, ntorga approved these changes

2024-01-12 13:46 UTC, merged