Feat/recreate mapping when update port binding
speedianet/os pull request #8
Opened 2024-01-11 19:34 UTC by polillomm

2024-01-11 20:25 UTC, ntorga requested changes

2024-01-11 20:25 UTC, ntorga commented on src/domain/useCase/updateService.go
> +				break
Esse break aqui tá certo? Você não precisa continuar por todos os vhosts?

2024-01-11 20:25 UTC, ntorga commented on src/infra/virtualHostCmdRepo.go
> +	return nil
return repo.AddMapping(mappingDto)

2024-01-11 20:31 UTC, polillomm commented on src/domain/useCase/updateService.go
> +				break
Tá errado esse break. Removido!

2024-01-11 20:32 UTC, polillomm commented on src/infra/virtualHostCmdRepo.go
> +	return nil
Ajustado!

2024-01-12 13:47 UTC, ntorga approved these changes

2024-01-12 13:47 UTC, merged